# Generated by Django 5.1 on 2024-08-14 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='media',
            field=models.ImageField(blank=True, null=True, upload_to='media/% Y/% m/% d/'),
        ),
    ]
